#!/bin/sh
# Start jdtls with its own writable config and data folders in HOME.

set -eu

# --- GLOBALS ---
CONFIG="$HOME/.cache/jdtls-config"
DATA="$HOME/.cache/jdtls-data"

# --- CODE ---
cp -r "$JDTLS_HOME/config_linux" "$CONFIG"

exec java \
  -Declipse.application=org.eclipse.jdt.ls.core.id1 \
  -Dosgi.bundles.defaultStartLevel=4 \
  -Declipse.product=org.eclipse.jdt.ls.core.product \
  -Dlog.level=ERROR \
  -Xms64m \
  -Xmx512m \
  -XX:+UseSerialGC \
  -XX:TieredStopAtLevel=1 \
  --add-modules=ALL-SYSTEM \
  --add-opens java.base/java.util=ALL-UNNAMED \
  --add-opens java.base/java.lang=ALL-UNNAMED \
  -jar "$(ls "$JDTLS_HOME"/plugins/org.eclipse.equinox.launcher_*.jar)" \
  -configuration "$CONFIG" \
  -data "$DATA"
